// seed.js — demo content so WYD Chicago looks ALIVE on first load with no backend.
//
// Everything here is FICTIONAL and clearly labeled (canon §9): fake hosts, fake usernames,
// no real addresses, no real minors' data. `exactAddress` uses obviously-made-up street names.
//
// startAt times are computed RELATIVE to the real current time at module load (new Date()),
// spread across the next ~3 weeks, so demo events are ALWAYS upcoming no matter when the
// site is opened. coverImageUrl is null on purpose — the frontend supplies a gradient fallback.
//
// Field names follow canon §4 exactly. Dates are ISO-8601 strings (mock convention, canon §9).

const NOW = new Date();

// Build a startAt N days from now, at a given local hour:minute. Returns ISO-8601.
function inDays(days, hour = 19, minute = 0) {
  const d = new Date(NOW.getTime());
  d.setDate(d.getDate() + days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}
// endAt = startAt + hours.
function plusHours(isoStart, hours) {
  return new Date(new Date(isoStart).getTime() + hours * 60 * 60 * 1000).toISOString();
}

// ---------------------------------------------------------------------------
// TAGS — event types + interests. emoji + chip color per canon tags/{tagId}.
// ---------------------------------------------------------------------------
export const SEED_TAGS = [
  // --- eventType ---
  { id: 'house-party',  label: 'House Party',  kind: 'eventType', emoji: '🏠', color: '#C44CFF', sort: 1 },
  { id: 'kickback',     label: 'Kickback',     kind: 'eventType', emoji: '🛋️', color: '#5B8CFF', sort: 2 },
  { id: 'concert',      label: 'Concert',      kind: 'eventType', emoji: '🎤', color: '#FF4D6D', sort: 3 },
  { id: 'game',         label: 'Game',         kind: 'eventType', emoji: '🏀', color: '#FFC83D', sort: 4 },
  { id: 'fundraiser',   label: 'Fundraiser',   kind: 'eventType', emoji: '💛', color: '#2EE6A6', sort: 5 },
  { id: 'open-mic',     label: 'Open Mic',     kind: 'eventType', emoji: '🎙️', color: '#C44CFF', sort: 6 },
  { id: 'sports',       label: 'Pickup Sports',kind: 'eventType', emoji: '⚽', color: '#2EE6A6', sort: 7 },
  { id: 'workshop',     label: 'Workshop',     kind: 'eventType', emoji: '🛠️', color: '#5B8CFF', sort: 8 },
  { id: 'market',       label: 'Market',       kind: 'eventType', emoji: '🛍️', color: '#FFC83D', sort: 9 },

  // --- interest ---
  { id: 'music',        label: 'Music',        kind: 'interest', emoji: '🎧', color: '#5B8CFF', sort: 20 },
  { id: 'hiphop',       label: 'Hip-Hop',      kind: 'interest', emoji: '🔥', color: '#FF4D6D', sort: 21 },
  { id: 'basketball',   label: 'Basketball',   kind: 'interest', emoji: '🏀', color: '#FFC83D', sort: 22 },
  { id: 'soccer',       label: 'Soccer',       kind: 'interest', emoji: '⚽', color: '#2EE6A6', sort: 23 },
  { id: 'art',          label: 'Art',          kind: 'interest', emoji: '🎨', color: '#C44CFF', sort: 24 },
  { id: 'gaming',       label: 'Gaming',       kind: 'interest', emoji: '🎮', color: '#5B8CFF', sort: 25 },
  { id: 'food',         label: 'Food',         kind: 'interest', emoji: '🍕', color: '#FF4D6D', sort: 26 },
  { id: 'dance',        label: 'Dance',        kind: 'interest', emoji: '💃', color: '#C44CFF', sort: 27 },
  { id: 'skating',      label: 'Skating',      kind: 'interest', emoji: '🛹', color: '#FFC83D', sort: 28 },
  { id: 'photography',  label: 'Photography',  kind: 'interest', emoji: '📷', color: '#5B8CFF', sort: 29 },
  { id: 'volunteering', label: 'Volunteering', kind: 'interest', emoji: '🤝', color: '#2EE6A6', sort: 30 },
  { id: 'fashion',      label: 'Fashion',      kind: 'interest', emoji: '🧥', color: '#FF4D6D', sort: 31 },
  { id: 'film',         label: 'Film',         kind: 'interest', emoji: '🎬', color: '#C44CFF', sort: 32 },
];

// ---------------------------------------------------------------------------
// USERS — a built-in admin + a handful of demo teens for the friends feature.
// birthYear chosen so ages land in the 14–18 range for 2026.
// (Mock passwords live in data.js, not here — seed only holds profile docs.)
// ---------------------------------------------------------------------------
export const SEED_USERS = [
  {
    uid: 'admin',
    displayName: 'WYD Team',
    username: 'wydteam',
    avatarUrl: null,
    bio: 'we run the city 🌃 (demo admin)',
    birthYear: 2000,
    gradeYear: null,
    neighborhood: 'Loop',
    interests: ['music', 'hiphop', 'basketball'],
    snapchatUsername: 'wydchicago',
    instagramUsername: 'wydchicago',
    role: 'admin',
    savedEvents: [],
    emailVerified: true,
  },
  {
    uid: 'u_maya',
    displayName: 'Maya R.',
    username: 'mayaaa',
    avatarUrl: null,
    bio: 'pilsen 🎨 always down',
    birthYear: 2009,
    gradeYear: 'Junior',
    neighborhood: 'Pilsen',
    interests: ['art', 'music', 'photography', 'dance'],
    snapchatUsername: 'maya.r',
    instagramUsername: 'maya.shoots',
    role: 'user',
    savedEvents: [],
    emailVerified: true,
  },
  {
    uid: 'u_deon',
    displayName: 'Deon W.',
    username: 'deon',
    avatarUrl: null,
    bio: 'hoops > everything 🏀',
    birthYear: 2008,
    gradeYear: 'Senior',
    neighborhood: 'Hyde Park',
    interests: ['basketball', 'hiphop', 'gaming'],
    snapchatUsername: 'deon.buckets',
    instagramUsername: 'deonw',
    role: 'user',
    savedEvents: [],
    emailVerified: true,
  },
  {
    uid: 'u_priya',
    displayName: 'Priya S.',
    username: 'priya',
    avatarUrl: null,
    bio: 'open mic regular 🎙️',
    birthYear: 2010,
    gradeYear: 'Sophomore',
    neighborhood: 'Lincoln Park',
    interests: ['music', 'art', 'film', 'fashion'],
    snapchatUsername: 'priya.s',
    instagramUsername: 'priyasings',
    role: 'user',
    savedEvents: [],
    emailVerified: true,
  },
  {
    uid: 'u_jordan',
    displayName: 'Jordan T.',
    username: 'jordan',
    avatarUrl: null,
    bio: 'skate / soccer / snacks 🛹',
    birthYear: 2009,
    gradeYear: 'Junior',
    neighborhood: 'Logan Square',
    interests: ['skating', 'soccer', 'food', 'gaming'],
    snapchatUsername: 'jordant',
    instagramUsername: 'jordan.t',
    role: 'host', // demo host — can create events without full admin powers
    savedEvents: [],
    emailVerified: true,
  },
];

// ---------------------------------------------------------------------------
// EVENTS — ~12 demo events. Varied eventTypes + neighborhoods (canon list).
// All start in the future (relative to load). counts are pre-seeded for hype.
// ---------------------------------------------------------------------------
function makeEvent(e) {
  const upvotes = e.upvotes ?? 0;
  const downvotes = e.downvotes ?? 0;
  return {
    title: e.title,
    description: e.description,
    eventType: e.eventType,
    tags: e.tags || [],
    hostId: e.hostId ?? null,
    hostName: e.hostName,
    coverImageUrl: null,
    images: [],
    startAt: e.startAt,
    endAt: e.endAt ?? plusHours(e.startAt, 4),
    venueName: e.venueName ?? null,
    neighborhood: e.neighborhood,
    approxArea: e.approxArea,
    exactAddress: e.exactAddress ?? null,
    priceCents: e.priceCents ?? 0,
    capacity: e.capacity ?? null,
    ageMin: e.ageMin ?? 14,
    ageMax: e.ageMax ?? 18,
    recommendedFor: e.recommendedFor || [],
    committedCount: e.committedCount ?? 0,
    interestedCount: e.interestedCount ?? 0,
    upvotes,
    downvotes,
    voteScore: upvotes - downvotes,
    status: e.status ?? 'published',
    isFeatured: e.isFeatured ?? false,
    createdBy: e.createdBy ?? 'admin',
    // id is attached below so each event is self-contained.
    id: e.id,
  };
}

export const SEED_EVENTS = [
  makeEvent({
    id: 'ev_rooftop',
    title: 'Rooftop Kickback — Sunset Set',
    description: "Chill rooftop hang, good music, golden hour photos. Bring a friend, vibe out. (Demo event — totally fictional.)",
    eventType: 'kickback',
    tags: ['music', 'photography', 'food'],
    hostName: 'WYD Team',
    startAt: inDays(0, 18, 30),
    neighborhood: 'West Loop',
    approxArea: 'West Loop',
    exactAddress: '742 W Imaginary St, Chicago, IL',
    recommendedFor: ['music', 'photography'],
    committedCount: 34, interestedCount: 58, upvotes: 71, downvotes: 4,
    isFeatured: true,
  }),
  makeEvent({
    id: 'ev_houseparty',
    title: 'End-of-Finals House Party 🎉',
    description: "Finals are OVER. Come celebrate. Music loud, no drama, hosts checking IDs at the door. (Demo only.)",
    eventType: 'house-party',
    tags: ['hiphop', 'dance', 'music'],
    hostName: '@kevinp',
    hostId: 'u_demo_host',
    startAt: inDays(1, 21, 0),
    neighborhood: 'Wicker Park',
    approxArea: 'Wicker Park',
    exactAddress: '1900 N Pretend Ave, Chicago, IL',
    recommendedFor: ['hiphop', 'dance'],
    committedCount: 88, interestedCount: 120, upvotes: 134, downvotes: 11,
    isFeatured: true,
  }),
  makeEvent({
    id: 'ev_openmic',
    title: 'Teen Open Mic Night',
    description: "Sing, rap, spoken word, comedy — the stage is yours for 5 min. Sign up at the door. Supportive crowd only. (Fictional demo.)",
    eventType: 'open-mic',
    tags: ['music', 'art', 'hiphop'],
    hostName: 'WYD Team',
    startAt: inDays(2, 19, 0),
    neighborhood: 'Lincoln Park',
    approxArea: 'Lincoln Park',
    exactAddress: '333 W Madeup Pkwy, Chicago, IL',
    recommendedFor: ['music', 'art'],
    committedCount: 22, interestedCount: 40, upvotes: 49, downvotes: 2,
  }),
  makeEvent({
    id: 'ev_3v3',
    title: '3v3 Basketball Run',
    description: "Open gym, full-court, first to 11. All skill levels — run it back till the lights go off. (Demo content.)",
    eventType: 'game',
    tags: ['basketball', 'hiphop'],
    hostName: '@deon',
    hostId: 'u_deon',
    startAt: inDays(3, 17, 0),
    neighborhood: 'Hyde Park',
    approxArea: 'Hyde Park',
    exactAddress: '5500 S Notreal Ct, Chicago, IL',
    recommendedFor: ['basketball'],
    committedCount: 18, interestedCount: 25, upvotes: 33, downvotes: 1,
  }),
  makeEvent({
    id: 'ev_artmarket',
    title: 'Teen Art + Thrift Market',
    description: "Sell your art, flip your fits, find one-of-one pieces. Free tables for teen vendors — DM to grab one. (Demo only.)",
    eventType: 'market',
    tags: ['art', 'fashion', 'photography'],
    hostName: 'WYD Team',
    startAt: inDays(4, 13, 0),
    neighborhood: 'Pilsen',
    approxArea: 'Pilsen',
    exactAddress: '1100 W Fauxbroke Rd, Chicago, IL',
    recommendedFor: ['art', 'fashion'],
    committedCount: 41, interestedCount: 77, upvotes: 60, downvotes: 5,
  }),
  makeEvent({
    id: 'ev_soccer',
    title: 'Sunday Pickup Soccer ⚽',
    description: "Casual pickup, jerseys vs no-jerseys. Cleats optional, good vibes required. (Fictional demo.)",
    eventType: 'sports',
    tags: ['soccer', 'food'],
    hostName: '@jordan',
    hostId: 'u_jordan',
    startAt: inDays(6, 11, 0),
    neighborhood: 'Logan Square',
    approxArea: 'Logan Square',
    exactAddress: '2700 N Invented Blvd, Chicago, IL',
    recommendedFor: ['soccer'],
    committedCount: 16, interestedCount: 19, upvotes: 21, downvotes: 0,
  }),
  makeEvent({
    id: 'ev_fundraiser',
    title: 'Mutual Aid Bake Sale 💛',
    description: "Baked goods, all proceeds to a local food pantry. Bring cash or tap to pay. Come hang and do some good. (Demo content.)",
    eventType: 'fundraiser',
    tags: ['volunteering', 'food'],
    hostName: 'WYD Team',
    startAt: inDays(7, 12, 0),
    neighborhood: 'Rogers Park',
    approxArea: 'Rogers Park',
    exactAddress: '7000 N Faketon St, Chicago, IL',
    recommendedFor: ['volunteering', 'food'],
    committedCount: 27, interestedCount: 38, upvotes: 44, downvotes: 1,
  }),
  makeEvent({
    id: 'ev_concert',
    title: 'All-Ages Local Concert 🎤',
    description: "Three teen bands, one stage. Loud, sweaty, all-ages. Doors at 6. (Fictional demo — no real venue.)",
    eventType: 'concert',
    tags: ['music', 'hiphop', 'dance'],
    hostName: '@thebands',
    hostId: 'u_demo_host',
    startAt: inDays(9, 18, 0),
    neighborhood: 'Avondale',
    approxArea: 'Avondale',
    exactAddress: '3300 W Pretendo Ave, Chicago, IL',
    priceCents: 1000,
    recommendedFor: ['music', 'hiphop'],
    committedCount: 64, interestedCount: 92, upvotes: 88, downvotes: 7,
    isFeatured: true,
  }),
  makeEvent({
    id: 'ev_gamenight',
    title: 'Smash + Mario Kart Tourney 🎮',
    description: "Bracket-style, bring your controller. Winner gets bragging rights + snacks. (Demo only.)",
    eventType: 'kickback',
    tags: ['gaming', 'food'],
    hostName: 'WYD Team',
    startAt: inDays(10, 16, 0),
    neighborhood: 'Bridgeport',
    approxArea: 'Bridgeport',
    exactAddress: '900 W Notrealson Dr, Chicago, IL',
    recommendedFor: ['gaming'],
    committedCount: 30, interestedCount: 35, upvotes: 52, downvotes: 3,
  }),
  makeEvent({
    id: 'ev_skate',
    title: 'Skate Meetup + Photo Walk 🛹',
    description: "Cruise the park, film some clips, get shots. Beginners welcome, we go slow. (Fictional demo.)",
    eventType: 'kickback',
    tags: ['skating', 'photography', 'film'],
    hostName: '@jordan',
    hostId: 'u_jordan',
    startAt: inDays(12, 15, 0),
    neighborhood: 'Uptown',
    approxArea: 'Uptown',
    exactAddress: '4500 N Madeupton St, Chicago, IL',
    recommendedFor: ['skating', 'photography'],
    committedCount: 14, interestedCount: 20, upvotes: 26, downvotes: 1,
  }),
  makeEvent({
    id: 'ev_workshop',
    title: 'Beat-Making Workshop 🎧',
    description: "Learn to cook up beats from scratch on free software. Laptops provided, just show up. (Demo content.)",
    eventType: 'workshop',
    tags: ['music', 'hiphop', 'art'],
    hostName: 'WYD Team',
    startAt: inDays(15, 17, 30),
    neighborhood: 'South Shore',
    approxArea: 'South Shore',
    exactAddress: '7100 S Imaginary Ave, Chicago, IL',
    recommendedFor: ['music', 'hiphop'],
    committedCount: 19, interestedCount: 31, upvotes: 40, downvotes: 2,
  }),
  makeEvent({
    id: 'ev_dance',
    title: 'Teen Dance Battle 💃🔥',
    description: "Cyphers, crews, 1v1s. Come throw down or just watch the heat. Judges from the city's best. (Fictional demo.)",
    eventType: 'concert',
    tags: ['dance', 'hiphop', 'music'],
    hostName: 'WYD Team',
    startAt: inDays(18, 19, 0),
    neighborhood: 'Humboldt Park',
    approxArea: 'Humboldt Park',
    exactAddress: '1600 N Faketon Blvd, Chicago, IL',
    recommendedFor: ['dance', 'hiphop'],
    committedCount: 47, interestedCount: 70, upvotes: 81, downvotes: 6,
    isFeatured: true,
  }),
  // One DRAFT so admin tooling has something unpublished to act on.
  makeEvent({
    id: 'ev_draft_filmnight',
    title: 'Outdoor Film Night (coming soon)',
    description: "Movie under the stars, bring a blanket. Still locking the title — vote in comments. (Demo draft.)",
    eventType: 'kickback',
    tags: ['film', 'food', 'art'],
    hostName: 'WYD Team',
    startAt: inDays(20, 20, 0),
    neighborhood: 'Andersonville',
    approxArea: 'Andersonville',
    exactAddress: '5200 N Notreal St, Chicago, IL',
    recommendedFor: ['film'],
    committedCount: 0, interestedCount: 0, upvotes: 0, downvotes: 0,
    status: 'draft',
  }),
];
